import type { Article, CatalogItem, User } from '@/lib/types'

export const CURRENT_USER_ID = 'u-agent-01'

export const USERS: User[] = [
  { id: 'u-agent-01', name: 'Ravi Menon', email: 'ravi.menon@meridian.io', role: 'agent', team: 'Service Desk', avatarColor: 'var(--chart-1)', initials: 'RM' },
  { id: 'u-agent-02', name: 'Dana Whitfield', email: 'dana.w@meridian.io', role: 'agent', team: 'Service Desk', avatarColor: 'var(--chart-2)', initials: 'DW' },
  { id: 'u-agent-03', name: 'Sofia Alvarez', email: 'sofia.a@meridian.io', role: 'agent', team: 'Endpoint', avatarColor: 'var(--chart-3)', initials: 'SA' },
  { id: 'u-agent-04', name: 'Marcus Boyd', email: 'marcus.b@meridian.io', role: 'agent', team: 'Network', avatarColor: 'var(--chart-4)', initials: 'MB' },
  { id: 'u-lead-01', name: 'Priya Nair', email: 'priya.n@meridian.io', role: 'lead', team: 'Service Desk', avatarColor: 'var(--chart-5)', initials: 'PN' },
  { id: 'u-emp-01', name: 'Tom Becker', email: 'tom.becker@meridian.io', role: 'employee', team: 'Finance', avatarColor: 'var(--chart-2)', initials: 'TB' },
  { id: 'u-emp-02', name: 'Lena Cho', email: 'lena.cho@meridian.io', role: 'employee', team: 'Marketing', avatarColor: 'var(--chart-3)', initials: 'LC' },
  { id: 'u-emp-03', name: 'Omar Haddad', email: 'omar.h@meridian.io', role: 'employee', team: 'Sales', avatarColor: 'var(--chart-1)', initials: 'OH' },
  { id: 'u-emp-04', name: 'Grace Park', email: 'grace.park@meridian.io', role: 'employee', team: 'HR', avatarColor: 'var(--chart-4)', initials: 'GP' },
  { id: 'u-emp-05', name: 'Ivan Petrov', email: 'ivan.p@meridian.io', role: 'employee', team: 'Engineering', avatarColor: 'var(--chart-5)', initials: 'IP' },
]

export const AGENT_IDS = USERS.filter((u) => u.role === 'agent').map((u) => u.id)
export const EMPLOYEE_IDS = USERS.filter((u) => u.role === 'employee').map((u) => u.id)

export const CATALOG_ITEMS: CatalogItem[] = [
  { id: 'cat-01', title: 'New laptop', description: 'Request a standard-issue laptop for a new or replacement device.', category: 'Hardware', icon: 'Laptop', fulfillmentEstimate: '3–5 business days', defaultPriority: 'p3', fields: [{ label: 'Preferred model', type: 'select', required: true, options: ['MacBook Pro 14"', 'Dell Latitude', 'Lenovo ThinkPad'] }, { label: 'Justification', type: 'textarea', required: true }] },
  { id: 'cat-02', title: 'Monitor request', description: 'Additional or replacement external monitor for your workstation.', category: 'Hardware', icon: 'Monitor', fulfillmentEstimate: '2–4 business days', defaultPriority: 'p4', fields: [{ label: 'Screen size', type: 'select', required: true, options: ['24"', '27"', '32" Ultrawide'] }] },
  { id: 'cat-03', title: 'Headset / peripherals', description: 'Keyboards, mice, headsets and other desk peripherals.', category: 'Hardware', icon: 'Headphones', fulfillmentEstimate: '1–3 business days', defaultPriority: 'p4', fields: [{ label: 'Item needed', type: 'text', required: true }] },
  { id: 'cat-04', title: 'Software license', description: 'Request access to a licensed application (Adobe, Figma, etc.).', category: 'Software', icon: 'Package', fulfillmentEstimate: '1–2 business days', defaultPriority: 'p3', fields: [{ label: 'Application', type: 'text', required: true }, { label: 'Business reason', type: 'textarea', required: true }] },
  { id: 'cat-05', title: 'VPN access', description: 'Remote network access via corporate VPN.', category: 'Access', icon: 'ShieldCheck', fulfillmentEstimate: 'Same day', defaultPriority: 'p2', fields: [{ label: 'Reason for access', type: 'textarea', required: true }] },
  { id: 'cat-06', title: 'Shared drive access', description: 'Access to a team or departmental shared folder.', category: 'Access', icon: 'FolderKey', fulfillmentEstimate: '1 business day', defaultPriority: 'p3', fields: [{ label: 'Folder / share name', type: 'text', required: true }] },
  { id: 'cat-07', title: 'Password reset', description: 'Reset a forgotten or expired account password.', category: 'Access', icon: 'KeyRound', fulfillmentEstimate: 'Same day', defaultPriority: 'p2', fields: [{ label: 'Account / system', type: 'text', required: true }] },
  { id: 'cat-08', title: 'New hire onboarding', description: 'Provision accounts, hardware and access for a new team member.', category: 'Onboarding', icon: 'UserPlus', fulfillmentEstimate: '5 business days', defaultPriority: 'p2', fields: [{ label: 'New hire name', type: 'text', required: true }, { label: 'Start date', type: 'text', required: true }, { label: 'Department', type: 'text', required: true }] },
  { id: 'cat-09', title: 'Offboarding', description: 'Deactivate accounts and reclaim equipment for a departing employee.', category: 'Onboarding', icon: 'UserMinus', fulfillmentEstimate: '2 business days', defaultPriority: 'p2', fields: [{ label: 'Employee name', type: 'text', required: true }, { label: 'Last day', type: 'text', required: true }] },
  { id: 'cat-10', title: 'Wi-Fi / connectivity', description: 'Report or request help with office network connectivity.', category: 'Connectivity', icon: 'Wifi', fulfillmentEstimate: 'Same day', defaultPriority: 'p2', fields: [{ label: 'Location / floor', type: 'text', required: true }, { label: 'Describe the issue', type: 'textarea', required: true }] },
  { id: 'cat-11', title: 'Conference room AV', description: 'Support for meeting room displays, cameras and audio.', category: 'Connectivity', icon: 'Video', fulfillmentEstimate: 'Same day', defaultPriority: 'p3', fields: [{ label: 'Room', type: 'text', required: true }] },
  { id: 'cat-12', title: 'Email distribution list', description: 'Create or modify an email distribution / group alias.', category: 'Software', icon: 'Mail', fulfillmentEstimate: '1 business day', defaultPriority: 'p4', fields: [{ label: 'List name', type: 'text', required: true }, { label: 'Members', type: 'textarea', required: true }] },
]

export const ARTICLES: Article[] = [
  { id: 'kb-01', title: 'How to reset your corporate password', category: 'Access', authorId: 'u-agent-01', updatedAt: '2026-07-10T09:00:00.000Z', tags: ['password', 'account'], helpfulCount: 142, relatedArticleIds: ['kb-02', 'kb-05'], body: '## Overview\nIf your password has expired or you have forgotten it, follow these steps to regain access.\n\n## Steps\n1. Navigate to the self-service portal.\n2. Select **Forgot password**.\n3. Verify your identity via the code sent to your registered device.\n4. Choose a new password meeting the complexity policy.\n\n## Tips\nPasswords must be at least 12 characters and include a number and symbol.' },
  { id: 'kb-02', title: 'Connecting to the corporate VPN', category: 'Connectivity', authorId: 'u-agent-04', updatedAt: '2026-07-12T14:30:00.000Z', tags: ['vpn', 'remote', 'network'], helpfulCount: 98, relatedArticleIds: ['kb-01', 'kb-06'], body: '## Overview\nThe VPN gives you secure access to internal resources from outside the office.\n\n## Steps\n1. Open the VPN client from your applications.\n2. Sign in with your corporate credentials.\n3. Approve the multi-factor prompt.\n4. Confirm the status indicator shows **Connected**.' },
  { id: 'kb-03', title: 'Setting up a new laptop', category: 'Hardware', authorId: 'u-agent-03', updatedAt: '2026-07-08T11:15:00.000Z', tags: ['laptop', 'onboarding', 'device'], helpfulCount: 76, relatedArticleIds: ['kb-04', 'kb-07'], body: '## Overview\nGetting your new device ready for work takes about 20 minutes.\n\n## Steps\n1. Power on and connect to Wi-Fi.\n2. Sign in with your corporate account.\n3. Let the management profile install required apps.\n4. Enable disk encryption when prompted.' },
  { id: 'kb-04', title: 'Requesting additional monitors', category: 'Hardware', authorId: 'u-agent-02', updatedAt: '2026-07-05T16:45:00.000Z', tags: ['monitor', 'hardware'], helpfulCount: 41, relatedArticleIds: ['kb-03'], body: '## Overview\nStandard workstations support up to two external monitors.\n\n## Steps\n1. Submit a Monitor request from the service catalog.\n2. Select your preferred size.\n3. Collect from the IT desk once fulfilled.' },
  { id: 'kb-05', title: 'Enabling multi-factor authentication', category: 'Access', authorId: 'u-agent-01', updatedAt: '2026-07-14T10:00:00.000Z', tags: ['mfa', 'security', 'account'], helpfulCount: 120, relatedArticleIds: ['kb-01'], body: '## Overview\nMFA adds a second layer of protection to your account.\n\n## Steps\n1. Open your account security settings.\n2. Choose **Add authentication method**.\n3. Scan the QR code with an authenticator app.\n4. Enter the generated code to confirm.' },
  { id: 'kb-06', title: 'Troubleshooting Wi-Fi connectivity', category: 'Connectivity', authorId: 'u-agent-04', updatedAt: '2026-07-11T13:20:00.000Z', tags: ['wifi', 'network'], helpfulCount: 88, relatedArticleIds: ['kb-02'], body: '## Overview\nMost connectivity issues resolve with a few quick checks.\n\n## Steps\n1. Toggle Wi-Fi off and on.\n2. Forget and rejoin the corporate network.\n3. Confirm you are in range of an access point.\n4. Restart your device if the issue persists.' },
  { id: 'kb-07', title: 'Installing licensed software', category: 'Software', authorId: 'u-agent-03', updatedAt: '2026-07-09T08:30:00.000Z', tags: ['software', 'license'], helpfulCount: 54, relatedArticleIds: ['kb-08'], body: '## Overview\nLicensed applications are installed through the managed software center.\n\n## Steps\n1. Open the Software Center.\n2. Find the approved application.\n3. Click **Install** and wait for completion.' },
  { id: 'kb-08', title: 'Accessing shared drives', category: 'Access', authorId: 'u-agent-02', updatedAt: '2026-07-06T12:00:00.000Z', tags: ['drive', 'files', 'access'], helpfulCount: 33, relatedArticleIds: ['kb-07'], body: '## Overview\nShared drives require membership in the relevant access group.\n\n## Steps\n1. Request access via the catalog.\n2. Once approved, map the drive using the provided path.' },
  { id: 'kb-09', title: 'Booking and using conference room AV', category: 'Connectivity', authorId: 'u-agent-04', updatedAt: '2026-07-13T15:00:00.000Z', tags: ['av', 'meeting', 'room'], helpfulCount: 27, relatedArticleIds: ['kb-06'], body: '## Overview\nEvery room has a touch panel for display and audio control.\n\n## Steps\n1. Tap the panel to wake it.\n2. Select **Share screen** or **Start meeting**.\n3. Follow on-screen pairing instructions.' },
  { id: 'kb-10', title: 'New hire IT onboarding checklist', category: 'Onboarding', authorId: 'u-lead-01', updatedAt: '2026-07-15T09:45:00.000Z', tags: ['onboarding', 'checklist'], helpfulCount: 61, relatedArticleIds: ['kb-03', 'kb-05'], body: '## Overview\nUse this checklist to ensure new team members are fully provisioned.\n\n## Checklist\n1. Account and email created.\n2. Hardware assigned and configured.\n3. MFA enrolled.\n4. Access groups granted.\n5. Welcome resources shared.' },
]
